version: '3'
services:
  # MySQL Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_db
      MYSQL_USER: cruduser
      MYSQL_PASSWORD: crudpassword
    ports:
      - "3306:3306"
    networks:
      - crud-network

  # PHP Service
  web:
    build: ./php
    container_name: php_web
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - crud-network

networks:
  crud-network:
    driver: bridge