version: '3.8'
services:
  web:
    image: php:8.2-apache
    container_name: crud-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: crud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookdb
    volumes:
      - db_data:/var/lib/mysql
      - ./src/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  db_data:
